rick_baby_homepage:
    pattern:  /baby
    defaults: { _controller: RickBabyBundle:Baby:index }

rick_baby_new:
    pattern:  /baby/new
    defaults: { _controller: RickBabyBundle:Baby:new }

rick_baby_profile:
    pattern:  /baby/profile
    defaults: { _controller: RickBabyBundle:Baby:profile }

rick_baby_history:
    pattern:  /baby/history
    defaults: { _controller: RickBabyBundle:Baby:history }