parameters:
#    rick_baby.example.class: Rick\BabyBundle\Example

services:
#    rick_baby.example:
#        class: %rick_baby.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
